import { z } from "zod";
import {
  CreateFunnelRequest,
  CreateFunnelResponse,
  createFunnelRequest,
  createFunnelResponse,
} from "../../../types/funnel/create";
import { getPrisma } from "../../../lib/prisma";
import { hasPermissionToCreateFunnel } from "../../../helpers/funnel/create";
import {
  generateSlug,
  generateDateSlug,
  generateUniqueSlug,
} from "../../../helpers/funnel/shared";
import { format } from "date-fns";
import { cacheService } from "../../cache/cache.service";

export const createFunnel = async (
  userId: number,
  data: Partial<CreateFunnelRequest>
): Promise<CreateFunnelResponse> => {
  let validatedData: CreateFunnelRequest = {} as CreateFunnelRequest;

  try {
    if (!userId) throw new Error("User ID is required");

    validatedData = createFunnelRequest.parse(data);

    if (!validatedData.workspaceId) {
      throw new Error("Please select a workspace to create the funnel in");
    }

    const prisma = getPrisma();

    const workspace = await prisma.workspace.findUnique({
      where: { id: validatedData.workspaceId },
      select: {
        id: true,
        name: true,
        ownerId: true,
        allocatedFunnels: true,
        owner: {
          select: {
            id: true,
            maximumFunnels: true,
          },
        },
      },
    });

    if (!workspace) {
      throw new Error("The selected workspace does not exist");
    }

    // Check if workspace has reached its allocated funnel limit
    const currentFunnelCount = await prisma.funnel.count({
      where: { workspaceId: validatedData.workspaceId },
    });

    if (currentFunnelCount >= workspace.allocatedFunnels) {
      throw new Error("This workspace has reached its maximum number of funnels.");
    }

    // Check permissions
    const isOwner = workspace.ownerId === userId;

    if (!isOwner) {
      const member = await prisma.workspaceMember.findUnique({
        where: {
          userId_workspaceId: {
            userId: userId,
            workspaceId: validatedData.workspaceId,
          },
        },
        select: {
          role: true,
          permissions: true,
        },
      });

      if (!member) {
        throw new Error(
          `You don't have access to the "${workspace.name}" workspace. Please ask the workspace owner to invite you.`
        );
      }

      const canCreateFunnel = hasPermissionToCreateFunnel(
        member.role,
        member.permissions
      );

      if (!canCreateFunnel) {
        throw new Error(
          `You don't have permission to create funnels in this workspace. Please contact your workspace admin.`
        );
      }
    }

    // Generate slug based on name or user-provided slug
    let slug: string;

    if (validatedData.slug) {
      // User provided a slug, make it unique
      slug = await generateUniqueSlug(
        validatedData.slug,
        validatedData.workspaceId
      );
    } else {
      // Auto-generate slug from name
      const isAutoGeneratedName =
        validatedData.name === format(new Date(), "dd.MM.yyyy HH:mm");

      if (isAutoGeneratedName) {
        // For auto-generated date names, create date-based slug
        slug = generateDateSlug(new Date());
        slug = await generateUniqueSlug(slug, validatedData.workspaceId);
      } else {
        // For user-provided names, create slug from name
        try {
          const baseSlug = generateSlug(validatedData.name);
          slug = await generateUniqueSlug(baseSlug, validatedData.workspaceId);
        } catch (slugError) {
          // If slug generation fails due to invalid characters, throw user-friendly error
          if (
            slugError instanceof Error &&
            slugError.message.includes("invalid characters")
          ) {
            throw new Error(
              "Funnel name contains invalid characters. Please use letters, numbers, spaces, and hyphens only."
            );
          }
          throw slugError;
        }
      }
    }

    const result = await prisma.$transaction(async (tx) => {
      const funnel = await tx.funnel.create({
        data: {
          name: validatedData.name,
          slug: slug,
          status: validatedData.status,
          workspaceId: validatedData.workspaceId,
          createdBy: userId,
        },
      });

      const theme = await tx.theme.create({ data: {} });

      await tx.funnelSettings.create({
        data: {
          funnelId: funnel.id,
          defaultSeoTitle: null,
          defaultSeoDescription: null,
          defaultSeoKeywords: null,
          favicon: null,
          ogImage: null,
          googleAnalyticsId: null,
          facebookPixelId: null,
          cookieConsentText: null,
          privacyPolicyUrl: null,
          termsOfServiceUrl: null,
        },
      });

      const funnelWithTheme = await tx.funnel.update({
        where: { id: funnel.id },
        data: { themeId: theme.id },
        include: {
          theme: true,
          pages: {
            orderBy: { order: "asc" },
            select: {
              id: true,
              name: true,
              order: true,
              linkingId: true,
              seoTitle: true,
              seoDescription: true,
              seoKeywords: true,
            },
          },
        },
      });

      const homePage = await tx.page.create({
        data: {
          name: "Home",
          content: "",
          type: "PAGE", // Default type for home page
          order: 1,
          funnelId: funnel.id,
          linkingId: "home",
        },
      });

      // Add the home page to the funnel's pages array
      const funnelWithHomePage = {
        ...funnelWithTheme,
        pages: [
          {
            id: homePage.id,
            name: homePage.name,
            order: homePage.order,
            type: homePage.type,
            linkingId: homePage.linkingId,
            seoTitle: homePage.seoTitle,
            seoDescription: homePage.seoDescription,
            seoKeywords: homePage.seoKeywords,
          },
        ],
      };

      return { funnel: funnelWithHomePage, homePage };
    });

    try {
      // Cache the individual funnel with full data including pages (without content)
      const fullFunnelCacheKey = `workspace:${validatedData.workspaceId}:funnel:${result.funnel.id}:full`;
      const fullFunnelData = {
        id: result.funnel.id,
        name: result.funnel.name,
        slug: result.funnel.slug,
        status: result.funnel.status,
        workspaceId: result.funnel.workspaceId,
        createdBy: result.funnel.createdBy,
        themeId: result.funnel.themeId,
        createdAt: result.funnel.createdAt,
        updatedAt: result.funnel.updatedAt,
        theme: result.funnel.theme,
        pages: result.funnel.pages,
      };
      await cacheService.set(fullFunnelCacheKey, fullFunnelData, { ttl: 0 });

      // Cache the home page with content separately
      const pageCacheKey = `funnel:${result.funnel.id}:page:${result.homePage.id}:full`;
      const pageData = {
        id: result.homePage.id,
        name: result.homePage.name,
        content: result.homePage.content,
        order: result.homePage.order,
        type: result.homePage.type,
        linkingId: result.homePage.linkingId,
        seoTitle: result.homePage.seoTitle,
        seoDescription: result.homePage.seoDescription,
        seoKeywords: result.homePage.seoKeywords,
        funnelId: result.homePage.funnelId,
        createdAt: result.homePage.createdAt,
        updatedAt: result.homePage.updatedAt,
      };
      await cacheService.set(pageCacheKey, pageData, { ttl: 0 });

      // Update the workspace's all funnels cache
      const allFunnelsCacheKey = `workspace:${validatedData.workspaceId}:funnels:all`;
      let existingFunnels = await cacheService.get<any[]>(allFunnelsCacheKey);

      // If cache doesn't exist, fetch all funnels from database
      if (!existingFunnels) {
        const allFunnels = await prisma.funnel.findMany({
          where: { workspaceId: validatedData.workspaceId },
          include: {
            theme: true,
          },
          orderBy: { createdAt: "desc" },
        });

        existingFunnels = allFunnels.map((funnel) => ({
          id: funnel.id,
          name: funnel.name,
          slug: funnel.slug,
          status: funnel.status,
          workspaceId: funnel.workspaceId,
          createdBy: funnel.createdBy,
          themeId: funnel.themeId,
          createdAt: funnel.createdAt,
          updatedAt: funnel.updatedAt,
          theme: funnel.theme,
        }));
      } else {
        // Add the newly created funnel to the existing cache
        const funnelSummary = {
          id: result.funnel.id,
          name: result.funnel.name,
          slug: result.funnel.slug,
          status: result.funnel.status,
          workspaceId: result.funnel.workspaceId,
          createdBy: result.funnel.createdBy,
          themeId: result.funnel.themeId,
          createdAt: result.funnel.createdAt,
          updatedAt: result.funnel.updatedAt,
          theme: result.funnel.theme,
        };
        existingFunnels = [...existingFunnels, funnelSummary];
      }

      await cacheService.set(allFunnelsCacheKey, existingFunnels, { ttl: 0 });

      // Invalidate old list caches
      await cacheService.del(
        `workspace:${validatedData.workspaceId}:funnels:list`
      );

      await cacheService.del(
        `user:${userId}:workspace:${validatedData.workspaceId}:funnels`
      );
    } catch (cacheError) {
      console.warn("Cache update failed but funnel was created:", cacheError);
    }

    const response = {
      message: `Funnel created successfully!`,
      funnelId: result.funnel.id,
    };

    return createFunnelResponse.parse(response);
  } catch (error: unknown) {
    if (error instanceof z.ZodError) {
      const firstError = error.issues[0];
      throw new Error(`Invalid input: ${firstError.message}`);
    }
    if (error instanceof Error) {
      if (
        error.message.includes("Unique constraint failed") ||
        error.message.includes("duplicate key value") ||
        error.message.includes("P2002")
      ) {
        if (error.message.includes("slug")) {
          throw new Error(
            `This funnel name is already in use in your workspace. Please choose a different name.`
          );
        }
        throw new Error(
          `A funnel with the name "${
            validatedData.name || "provided"
          }" already exists in this workspace. Please choose a different name.`
        );
      }
      throw new Error(`Failed to create funnel: ${error.message}`);
    }
    throw new Error("Couldn't create the funnel. Please try again.");
  }
};