import {
  CreateFunnelRequest,
  CreateFunnelResponse,
  WorkspacePayload,
  WorkspaceMemberPayload,
} from "../../../types/funnel/create";
import {
  createFunnelPayloadFactory,
  createFunnelSettingsPayloadFactory,
  createHomePagePayloadFactory,
  updateFunnelWithThemePayloadFactory,
} from "../../../factories/funnel/create";
import { getPrisma } from "../../../lib/prisma";
import { hasPermissionToCreateFunnel } from "../../../helpers/funnel/create";
import {
  generateSlug,
  generateDateSlug,
  generateUniqueSlug,
} from "../../../helpers/funnel/shared";
import { format } from "date-fns";

export const createFunnel = async (
  userId: number,
  data: CreateFunnelRequest
): Promise<CreateFunnelResponse> => {
  if (!userId) throw new Error("User ID is required");

  if (!data.workspaceSlug) {
    throw new Error("Please select a workspace to create the funnel in");
  }

  const prisma = getPrisma();

  const workspace: WorkspacePayload = await prisma.workspace.findUniqueOrThrow({
    where: { slug: data.workspaceSlug },
    select: {
      id: true,
      name: true,
      ownerId: true,
      allocatedFunnels: true,
      owner: {
        select: {
          id: true,
          maximumFunnels: true,
        },
      },
    },
  });

  const currentFunnelCount = await prisma.funnel.count({
    where: { workspaceId: workspace.id },
  });

  if (currentFunnelCount >= workspace.allocatedFunnels) {
    throw new Error(
      "This workspace has reached its maximum number of funnels."
    );
  }

  const isOwner = workspace.ownerId === userId;

  if (!isOwner) {
    const member: WorkspaceMemberPayload | null =
      await prisma.workspaceMember.findUnique({
        where: {
          userId_workspaceId: {
            userId: userId,
            workspaceId: workspace.id,
          },
        },
        select: {
          role: true,
          permissions: true,
        },
      });

    if (!member) {
      throw new Error(
        `You don't have access to the "${workspace.name}" workspace. Please ask the workspace owner to invite you.`
      );
    }

    const canCreateFunnel = hasPermissionToCreateFunnel(
      member.role,
      member.permissions
    );

    if (!canCreateFunnel) {
      throw new Error(
        `You don't have permission to create funnels in this workspace. Please contact your workspace admin.`
      );
    }
  }

  let slug: string;

  if (data.slug) {
    slug = await generateUniqueSlug(data.slug, workspace.id);
  } else {
    const isAutoGeneratedName =
      data.name === format(new Date(), "dd.MM.yyyy HH:mm");
    if (isAutoGeneratedName) {
      slug = generateDateSlug(new Date());
      slug = await generateUniqueSlug(slug, workspace.id);
    } else {
      try {
        const baseSlug = generateSlug(data.name);
        slug = await generateUniqueSlug(baseSlug, workspace.id);
      } catch (slugError) {
        if (
          slugError instanceof Error &&
          slugError.message.includes("invalid characters")
        ) {
          throw new Error(
            "Funnel name contains invalid characters. Please use letters, numbers, spaces, and hyphens only."
          );
        }
        throw slugError;
      }
    }
  }

  const result = await prisma.$transaction(async (tx) => {
    const createFunnelData = createFunnelPayloadFactory(
      data.name,
      slug,
      data.status,
      workspace.id,
      userId
    );

    const funnel = await tx.funnel.create({
      data: createFunnelData,
    });

    const theme = await tx.theme.create({ data: {} });

    const createFunnelSettingsData = createFunnelSettingsPayloadFactory(
      funnel.id
    );

    await tx.funnelSettings.create({
      data: createFunnelSettingsData,
    });

    const updateFunnelData = updateFunnelWithThemePayloadFactory(theme.id);

    const funnelWithTheme = await tx.funnel.update({
      where: { id: funnel.id },
      data: updateFunnelData,
      include: {
        theme: true,
        pages: {
          orderBy: { order: "asc" },
          select: {
            id: true,
            name: true,
            order: true,
            linkingId: true,
            seoTitle: true,
            seoDescription: true,
            seoKeywords: true,
          },
        },
      },
    });

    const createHomePageData = createHomePagePayloadFactory(funnel.id);

    const homePage = await tx.page.create({
      data: createHomePageData,
    });

    const funnelWithHomePage = {
      ...funnelWithTheme,
      pages: [homePage],
    };

    return { funnel: funnelWithHomePage, homePage };
  });

  const response: CreateFunnelResponse = {
    message: `Funnel created successfully!`,
    funnelId: result.funnel.id,
    workspaceId: workspace.id,
  };

  return response;
};
