import {
  CreateFunnelRequest,
  CreateFunnelResponse,
  WorkspacePayload,
  WorkspaceMemberPayload,
  CreateFunnelPayload,
  CreateFunnelSettingsPayload,
  CreateHomePagePayload,
  UpdateFunnelWithThemePayload,
} from "../../../types/funnel/create";
import { getPrisma } from "../../../lib/prisma";
import { hasPermissionToCreateFunnel } from "../../../helpers/funnel/create";
import {
  generateSlug,
  generateDateSlug,
  generateUniqueSlug,
} from "../../../helpers/funnel/shared";
import { format } from "date-fns";

export const createFunnel = async (
  userId: number,
  data: CreateFunnelRequest
): Promise<{ response: CreateFunnelResponse; workspaceId: number }> => {
  if (!userId) throw new Error("User ID is required");

  if (!data.workspaceSlug) {
    throw new Error("Please select a workspace to create the funnel in");
  }

  const prisma = getPrisma();

  const workspace: WorkspacePayload | null = await prisma.workspace.findUnique({
    where: { slug: data.workspaceSlug },
    select: {
      id: true,
      name: true,
      ownerId: true,
      allocatedFunnels: true,
      owner: {
        select: {
          id: true,
          maximumFunnels: true,
        },
      },
    },
  });

  if (!workspace) {
    throw new Error(`The workspace was not found`);
  }

  const currentFunnelCount = await prisma.funnel.count({
    where: { workspaceId: workspace.id },
  });

  if (currentFunnelCount >= workspace.allocatedFunnels) {
    throw new Error(
      "This workspace has reached its maximum number of funnels."
    );
  }

  const isOwner = workspace.ownerId === userId;

  if (!isOwner) {
    const member: WorkspaceMemberPayload | null =
      await prisma.workspaceMember.findUnique({
        where: {
          userId_workspaceId: {
            userId: userId,
            workspaceId: workspace.id,
          },
        },
        select: {
          role: true,
          permissions: true,
        },
      });

    if (!member) {
      throw new Error(
        `You don't have access to the "${workspace.name}" workspace. Please ask the workspace owner to invite you.`
      );
    }

    const canCreateFunnel = hasPermissionToCreateFunnel(
      member.role,
      member.permissions
    );

    if (!canCreateFunnel) {
      throw new Error(
        `You don't have permission to create funnels in this workspace. Please contact your workspace admin.`
      );
    }
  }

  let slug: string;

  if (data.slug) {
    slug = await generateUniqueSlug(data.slug, workspace.id);
  } else {
    const isAutoGeneratedName =
      data.name === format(new Date(), "dd.MM.yyyy HH:mm");
    if (isAutoGeneratedName) {
      slug = generateDateSlug(new Date());
      slug = await generateUniqueSlug(slug, workspace.id);
    } else {
      try {
        const baseSlug = generateSlug(data.name);
        slug = await generateUniqueSlug(baseSlug, workspace.id);
      } catch (slugError) {
        if (
          slugError instanceof Error &&
          slugError.message.includes("invalid characters")
        ) {
          throw new Error(
            "Funnel name contains invalid characters. Please use letters, numbers, spaces, and hyphens only."
          );
        }
        throw slugError;
      }
    }
  }

  const result = await prisma.$transaction(async (tx) => {
    const createFunnelData: CreateFunnelPayload = {
      name: data.name,
      slug,
      status: data.status,
      workspaceId: workspace.id,
      createdBy: userId,
    };

    const funnel = await tx.funnel.create({
      data: createFunnelData,
    });

    const theme = await tx.theme.create({ data: {} });

    const createFunnelSettingsData: CreateFunnelSettingsPayload = {
      funnelId: funnel.id,
      defaultSeoTitle: null,
      defaultSeoDescription: null,
      defaultSeoKeywords: null,
      favicon: null,
      ogImage: null,
      googleAnalyticsId: null,
      facebookPixelId: null,
      cookieConsentText: null,
      privacyPolicyUrl: null,
      termsOfServiceUrl: null,
    };

    await tx.funnelSettings.create({
      data: createFunnelSettingsData,
    });

    const updateFunnelData: UpdateFunnelWithThemePayload = {
      themeId: theme.id,
    };

    const funnelWithTheme = await tx.funnel.update({
      where: { id: funnel.id },
      data: updateFunnelData,
      include: {
        theme: true,
        pages: {
          orderBy: { order: "asc" },
          select: {
            id: true,
            name: true,
            order: true,
            linkingId: true,
            seoTitle: true,
            seoDescription: true,
            seoKeywords: true,
          },
        },
      },
    });

    const createHomePageData: CreateHomePagePayload = {
      name: "Home",
      content: "",
      order: 1,
      funnelId: funnel.id,
      linkingId: "home",
    };

    const homePage = await tx.page.create({
      data: createHomePageData,
    });

    const funnelWithHomePage = {
      ...funnelWithTheme,
      pages: [
        {
          id: homePage.id,
          name: homePage.name,
          order: homePage.order,
          linkingId: homePage.linkingId,
          seoTitle: homePage.seoTitle,
          seoDescription: homePage.seoDescription,
          seoKeywords: homePage.seoKeywords,
          type: homePage.type,
        },
      ],
    };

    return { funnel: funnelWithHomePage, homePage };
  });

  const response: CreateFunnelResponse = {
    message: `Funnel created successfully!`,
    funnelId: result.funnel.id,
  };

  return { response, workspaceId: workspace.id };
};
