import {
  generateSlug,
  generateDateSlug,
  generateUniqueSlug,
} from "../../../../helpers/funnel/shared";

export const generateFunnelSlug = async (
  name: string,
  workspaceId: number,
  providedSlug?: string
): Promise<string> => {
  if (providedSlug) {
    return await generateUniqueSlug(providedSlug, workspaceId);
  }

  const isAutoGeneratedName = /^\d{2}\.\d{2}\.\d{4} \d{2}:\d{2}:\d{2}$/.test(name);

  if (isAutoGeneratedName) {
    const slug = generateDateSlug(new Date());
    return await generateUniqueSlug(slug, workspaceId);
  }

  try {
    const baseSlug = generateSlug(name);
    return await generateUniqueSlug(baseSlug, workspaceId);
  } catch (slugError) {
    if (
      slugError instanceof Error &&
      slugError.message.includes("invalid characters")
    ) {
      throw new Error(
        "Your funnel name has some special characters we can't use. Please stick to letters, numbers, spaces, and dashes."
      );
    }
    throw slugError;
  }
};
