-- AlterTable
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "partnerLevel" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "totalSales" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "commissionPercentage" DOUBLE PRECISION NOT NULL DEFAULT 5;
